allowBuilds:
  better-sqlite3: false
  core-js-pure: false
  dtrace-provider: false
  protobufjs: false
  re2: false
autoDedupe: true
minimumReleaseAge: 0
shellEmulator: true
trustLockfile: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 604800
